try6

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,8 +4,13 @@ indent() {
   sed -u 's/^/       /'
 }
 
-echo "-----> Found setup-janus.sh"
+echo "-----> Starting Janus install.."
 
-setup-janus.sh
+exec > >(tee aws_janus_build.log)
+exec 2>&1
+set -e
+################# COMPILE ############
+# Update and Upgrade, otherwise the build may fail due to inconsistencies
+sudo apt-get update -y && sudo apt-get upgrade -y
 
 echo "-----> Janus install complete"
